services:
  db:
    image: postgres:15-alpine
    container_name: rei-do-chopp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=reidochopp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432" 

  api:
    image: ghcr.io/bernardoabaurre/rei-do-chopp-api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=reidochopp;Username=postgres;Password=${DB_PASSWORD};
      - Jwt__SecretKey=${JWT_SECRET}
      - Email__ApiKeys__Public=${EMAIL_PUBLIC_KEY}
      - Email__ApiKeys__Private=${EMAIL_PRIVATE_KEY}
    depends_on:
      - db
    restart: always

  frontend:
    image: ghcr.io/bernardoabaurre/rei-do-chopp-site:latest
    ports:
      - "80:80"
    environment:
      - API_URL=http://104.236.2.50:5000
    restart: always

volumes:
  postgres_data:
