# Dockerfile.angular
FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build --configuration=production

FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/rei-do-chopp-site/browser /usr/share/nginx/html
EXPOSE 80
